name: Deploy Checkout Page

on:
  push:
    tags:
      - "v*-checkout-alpha"
      - "v*-checkout-prod"
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-checkout-prod')
    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 🚀 Deploy Checkout Page Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /home/billing-system-fg-linkbit/deployer/checkout-deployer.sh

  deploy-staging:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '-checkout-alpha')
    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 🚀 Deploy Checkout Page Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: /home/billing-system-fg-linkbit/deployer/checkout-staging-deployer.sh
