jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 103.190.112.107
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 1999
          script: /home/billing-system-fg-linkbit/deployer/dashboard-staging-deployer.sh
